# Generated by Django 3.2.1 on 2023-02-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phoneno', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phoneno', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phoneno', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
